name: Build APK with error reporting

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11

      - name: Set Gradle executable
        run: chmod +x ./gradlew

      - name: Build APK
        id: build_apk
        run: |
          set +e
          ./gradlew assembleDebug --stacktrace > build.log 2>&1
          echo "status=$?" >> $GITHUB_OUTPUT

      - name: Extract error log and send to Telegram
        if: steps.build_apk.outputs.status != 0
        run: |
          grep -iE "FAILURE|Exception|Caused by|error:|BUILD FAILED" build.log | tail -n 50 > error_short.log
          curl -F document=@error_short.log \
               -F chat_id=${{ secrets.CHAT_ID }} \
               -F caption="❌ Ошибка сборки CodeEditorPro" \
               "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendDocument"

      - name: Upload full log
        if: steps.build_apk.outputs.status != 0
        uses: actions/upload-artifact@v4
        with:
          name: full-log
          path: build.log

