name: Android WebView App Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    # Создание директории для хранения вебвью приложения
    - name: Create WebView app structure
      run: |
        mkdir -p android-webview-app/assets
        cp -r web-app/* android-webview-app/assets/
    
    # Настройка окружения Android
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    # Создание простого WebView приложения с помощью скрипта
    - name: Create WebView APK
      run: |
        chmod +x create_minimal_apk.sh
        ./create_minimal_apk.sh
    
    # Загрузка готового APK
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: code-editor-app
        path: app/build/outputs/apk/debug/app-debug.apk